// DO NOT EDIT (or do, whatever; I'm a sign, not a cop -- ¯\_(ツ)_/¯).
// Auto-generated by github.com/avamsi/eclipse/cli/eclipse.

package main

import (
	"github.com/avamsi/eclipse"
)

const _github_io_avamsi_eclipse_cli_docs = "eyJtYWluLkJhemVsIjoiIiwibWFpbi5CYXplbC5CdWlsZCI6IiIsIm1haW4uQmF6ZWwuQnVpbGQuQ1BVIjoiIiwibWFpbi5CYXplbC5FeGVjdXRlIjoiIiwibWFpbi5CYXplbC5TdHJpcCI6IihhbHdheXN8bmV2ZXJ8c29tZXRpbWVzKSIsIm1haW4uQmF6ZWwuXyI6IiIsIm1haW4uTW9iaWxlIjoiIiwibWFpbi5Nb2JpbGUuQnpsIjoiIiwibWFpbi5Nb2JpbGUuSW5zdGFsbCI6IiIsIm1haW4uTW9iaWxlLlVuaW5zdGFsbCI6IiJ9"

func main() {
	eclipse.Execute(_github_io_avamsi_eclipse_cli_docs, Bazel{}, Mobile{})
}
